### ISSUE TITLE
Move twss code to a package.

### ISSUE THREAD

**Issue by cycomachead** [cs10/Alonzo#104]
This one has a lot of dependencies and files, so it's clean things up a bit.

**Comment by aaaschmitt** [comment]
Screw this code.....it doesn't even work

**Comment by aaaschmitt** [comment]
I need to add more training data I guess

**Comment by aaaschmitt** [comment]
Maybe we just try this: https://www.npmjs.com/package/hubot-twss

**Comment by cycomachead** [comment]
Oh that's not bad. Except just saying `twss` is meh... :stuck_out_tongue:

**Comment by aaaschmitt** [comment]
I'm going to just remove this package honestly. It's crap. And more annoying than fun.....

**Comment by aaaschmitt** [comment]
Removed 4c801ca
