### ISSUE TITLE
Check Off Confirm Messages should better reference the sending message

### ISSUE THREAD

**Issue by cycomachead** [cs10/Alonzo#107]
When multiple people send check off commands at once, it's not clear whom the bot is repsonding to.

We could
* At mention the requester (`res.reply` instead of `send`)
* Add the SID(s) somewhere in the resulting text
* Do something else??

**Comment by aaaschmitt** [comment]
Done See f9b672740009f4d6d7106a68a92fabf97ec69137 and 327ade400fd6ca16d6c89c126bc224e12996ca5b.

Msg.reply for everything pretty much.  On error it tells TAs to enter into the gradebook, but LAs to check the sid and then talk to the Lab TA. For each successful checkoff it also sends back a pair of student name and sid if we want to do verification as Justin had suggested.
