### ISSUE TITLE
Update hubot-redis-brain + other Redis Updates

### ISSUE THREAD

**Issue by cycomachead** [cs10/Alonzo#114]
Hubot redid brain is using a realllllllly old version of the node-redis package. We should fork it and then upgrade 

I'd also like to move the primary brain location to Heroku Redis rather than Redis To Go because the analytics are better. Otherwise if we want a second Redis instance RedisLabs is a better provider.

**Comment by aaaschmitt** [comment]
I think heroku switched over our redis instance. But if we want to switch providers then we'll need to deal with that. I don't think there is any current data that needs to be persistent at this point in the semester.

**Comment by cycomachead** [comment]
Well, there's the checkoff log and the alias and other config stuff. I think I can ssh in and set something as an actual mirror in Redis, but idk exactly how to do that. It seems neat though...

**Comment by cycomachead** [comment]
And as far as 
This:
https://github.com/hubot-scripts/hubot-redis-brain/blob/master/package.json#L16
The current version has way more updates:
https://www.npmjs.com/package/redis

**Comment by aaaschmitt** [comment]
ok :/

**Comment by cycomachead** [comment]
I mean, if we really don't care about the data we could just remove the old brain, but I'd wait for a little while.

**Comment by cycomachead** [comment]
Well, I just bumped the redis packages. Migrating to a slack and we still seem to have old data around. lol
