### ISSUE TITLE
Figure out how to get heroku .env vars into travis

### ISSUE THREAD

**Issue by aaaschmitt** [cs10/Alonzo#117]
@cycomachead you might have a better idea of how to do this than me. This will enable true CI for alonzo once we get this and then deploy hooks working.

**Comment by cycomachead** [comment]
Installing `hk` didn't do it?

Surely we aren't the first people with this problem. :stuck_out_tongue: I think I've seen some stuff around, let me look.

**Comment by aaaschmitt** [comment]
I got permission denied because it wanted to access usr/local/bin/hk to do the install. If we enable sudo in travis then we run on their old architecture I think and get slower build times :/

**Comment by cycomachead** [comment]
Alright, well I might try a few other things. There is `heroku config --json` which uses the old version, that might be avaiable through apt-get ?

Or we can run things on an OS X box and install through `brew` but that seems like a pain

**Comment by aaaschmitt** [comment]
Yeah I'm gonna look into it more too. Also just FYI hk is deprecated in favor of the heroku toolbelt.  The problem is that heroku tool belt (command: heroku config) doesn't give you env variables in as nice of form. So text processing would need to be done before putting it into a text file. We should also think about how authentication will work on travis.

**Comment by cycomachead** [comment]
hk is deprecated?! Damn. I like it because it's fast. 

The regular toolbelt actually does have a JSON option which I quite like and will try that soon. Now that I discovered it! 🙃

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by aaaschmitt** [comment]
nice! Yeah sudo is not really an option. I just tried to run a job and it's been sitting for like 10 mins now in a queue. Before adding sudo it took less than 5 mins to run.

**Comment by aaaschmitt** [comment]
but do we need sudo to install the heroku toolbelt?

**Comment by cycomachead** [comment]
We would, but I think it's available through `apt-get` so that would work.

Actually, the heroku API would probably work well too, because we can just `curl` something.

`curl -n https://api.heroku.com/apps/alonzo/config-vars   -H "Accept: application/vnd.heroku+json; version=3"`
I don't know what kind of auth we need though...it worked for me without auth, which seems scary AF, but I'm assuming there's cooking or something it used? o_O

**Comment by aaaschmitt** [comment]
Ok I think I was able to download heroku toolbelt on travis. They made it a special add on so you don't need sudo. If you could modify \_dev-vars to use the toolbelt that would be good. On travis there is a HEROKU\_API\_KEY variable that should get used to authenticate (I think).

**Comment by cycomachead** [comment]
ok, yeah. I'll try to play around with this soon.

**Comment by cycomachead** [comment]
Also I think I know why deployments weren't working now so I might be able to fix that.

**Comment by cycomachead** [comment]
IT WORKED. IT WORKED.

**Comment by aaaschmitt** [comment]
YES
