### ISSUE TITLE
Add a list of autograder labs to lab checkoffs

### ISSUE THREAD

**Issue by aaaschmitt** [cs10/Alonzo#120]
So we don't show TAs labs that they shouldn't actually be checking off

**Comment by cycomachead** [comment]
The easiest way will be to fix the regex matching lab names.

**Comment by cycomachead** [comment]
https://github.com/cs10/Alonzo/blob/master/scripts/cs10/checkoffs.js#L317

We should probably just amend this to be something like `/$Lab (\d{1,2})/i`.

**Comment by aaaschmitt** [comment]
Well yeah but like right now there is a Autograder Lab 11 entry and also a Lab 11 Recursive Reporters entry. ideally neither of these would be displayed to the TAs

**Comment by cycomachead** [comment]
Yeah, so if we use the regex I suggested then those shouldn't be shown as valid labs.

**Comment by aaaschmitt** [comment]
No but I mean like currently we don't also want to show Lab 11 Recursive Reporters if there is also a Autograded version of it. Or do we?

**Comment by cycomachead** [comment]
Just don't want it to show the autograded labs. Lab 11 (non-autograded) shouldn't have been created, but since it was, then we should show it...because TAs were using it because things were confused.

**Comment by aaaschmitt** [comment]
Oh ok that works then. I was thinking we might want to hide both and then
we'd need something more complicated but that's chill.

**Comment by aaaschmitt** [comment]
I ended just filtering these labs out of the lab assignments cache. If you need access to the info on auto-graded labs use the allAssignments cache. see 70801a2
