### ISSUE TITLE
Lab Check Offs

### ISSUE THREAD

**Issue by cycomachead** [cs10/Alonzo#37]
- [x] Enable Room Checking
- [x] Add warning for full credit after deadline
- [x] Enable Only TAs to give full credit after deadline (skipped for previewing LA scores)
- [x] Fuzzy matching for text in LA room (or others)
- [x] write more code docs
- [ ] write some user docs
- [x] cache the bCourses assignments call
- [x] clear bcourses cache command
- [x] Refactor to use new POST w/ combined SID submissions

**Comment by aaaschmitt** [comment]
see #119
