### ISSUE TITLE
Have a package to autorestart the chatbot

### ISSUE THREAD

**Issue by cycomachead** [cs10/Alonzo#58]
Because people are mean and want to hurt Alonzo. :cry:

**Comment by aaaschmitt** [comment]
The deploy button should fix this correct #118? Or do we also want something else

**Comment by cycomachead** [comment]
Oh sorry, #118 is about the Heroku button - https://blog.heroku.com/archives/2014/8/7/heroku-button

I'm actually going to close this, because we haven't had heroku kill the bot automatically but we can't do anything if the overall node process dies, it seems. Or we should be able to, I don't know enough about Heroku really.
