### ISSUE TITLE
Caching Library

### ISSUE THREAD

**Issue by cycomachead** [cs10/Alonzo#74]
It would be good to have a generic UI for caching data in the robot brain

Date needs a key, cache date, and a cache length, and the values, and that's it?
This shouldn't be too terrible...

**Comment by aaaschmitt** [comment]
Right now we store objects that are {time: time_cached, cacheVal: data}. Do you want to do more than this?

**Comment by cycomachead** [comment]
> Do you want to do more than this?

I think we should have a cache_length attribute with each object. Because ideally, we don't need to refresh all things all that often.

(General assignments cache should be short, but staff caching could/should be long.)

**Comment by aaaschmitt** [comment]
Assignment Groups, Staff IDs and lab assignments are all fairly short and you get all of them in one api call anyways. Are you talking about like LA data being cached? Right now that is the only other thing that is being cached that is fairly lengthy..

**Comment by cycomachead** [comment]
Mostly, I was trying to avoid server calls if at all possible for chat commands -- even though they're 1 API, that can still be a 3s delay at times which can make the bot feel slow.

**Comment by aaaschmitt** [comment]
I added cache lengths in a recent commit so I'm going to close this.  Make new issues for specific cache wants/problems.
