### ISSUE TITLE
Clear / Refresh Cache on brain startup

### ISSUE THREAD

**Issue by cycomachead** [cs10/Alonzo#77]
This would be useful for handling bCourses data and would ensure config data matches cached data.

Basically, caches suck. Or the story of why everyone fails CS61C.

**Comment by aaaschmitt** [comment]
See here:
https://github.com/cs10/Alonzo/blob/master/scripts/cs10/cs10-caching.js

Hubot waits 10 seconds so that the brain can load from redis (the current hubot-redis plugin does not emit an event it looks like).

**Comment by cycomachead** [comment]
Tag d0f21966f53bd7cf0d7a7b6ef9778a3dce71d6ad
