### ISSUE TITLE
Caching Needs to switch for being enabled / disabled

### ISSUE THREAD

**Issue by cycomachead** [cs10/Alonzo#79]
Damn. I knew I hated caches.

**Comment by aaaschmitt** [comment]
This sounds terrible to implement. Why do we need this?

**Comment by cycomachead** [comment]
This would be a dev thing really, but I guess if we have easy re-freshing it's ok.

**Comment by cycomachead** [comment]
We shold set the caching time as a TCP-eqsue expoential backoff time based on how far into the semester things are and how stable bCourses is.

**Comment by aaaschmitt** [comment]
-__________-

**Comment by aaaschmitt** [comment]
I built this into the cache. Do we want a command or is it enough that you can now do:
```
var cs10Cache = require('./caching.js');
cs10Cache.disable()
cs10Cache.enable()
```

**Comment by cycomachead** [comment]
I think it'd be good as a command. Mostly so that if there are lots of bCourses changes we can disable stuff for a little while.

**Comment by aaaschmitt** [comment]
Ok this is done. There are now commands:
```
/enable cache
/disable cache
/is caching enabled?
```

the regexs are fairly lenient. See db8d25a

**Comment by cycomachead** [comment]
Cool! :+1:
