### ISSUE TITLE
Replace string concatenation with template `` strings

### ISSUE THREAD

**Issue by cycomachead** [cs10/Alonzo#85]
https://nodejs.org/api/util.html#util_util_format_format

**Comment by aaaschmitt** [comment]
I actually like template strings better....I've replaced most things with these. But there are still some pretty nasty string concatenations lying around

**Comment by cycomachead** [comment]
This was pre-knowing about template literals! LOL.

Yes, template strings are better.

**Comment by aaaschmitt** [comment]
Can we close this? This has be done in most places...... I'll leave it up to you @cycomachead

**Comment by cycomachead** [comment]
I think it's good now? We fixed most stuff right?
