### ISSUE TITLE
Add Testing Framework

### ISSUE THREAD

**Issue by aaaschmitt** [cs10/Alonzo#89]
This needs to happen. Testing all these things by hand is awful.

See:
http://leapfrogonline.io/articles/2015-11-09-testing-hubot-scripts/

**Comment by cycomachead** [comment]
:+1: :x: :100: 

So so so badly needed.

**Comment by cycomachead** [comment]
Also, basic but could be done: https://github.com/github/hubot/blob/master/bin/hubot#L19

**Comment by aaaschmitt** [comment]
OKAY IT IS THERE. Include tests in the ./tests folder and run with the command npm test. I have some issues with env variables currently but I have a couple basic tests written. I will open another issue though this is done for now 9c99b6874f368a732d1db855122ba4d57ef2c4b5
