### ISSUE TITLE
Fix Travis deploy email to be the committer email 

### ISSUE THREAD

**Issue by cycomachead** [cs10/Alonzo#97]

**Comment by aaaschmitt** [comment]
I have no idea how to do this easily since the travis deploy key is tied to a user :/

**Comment by cycomachead** [comment]
I think we might be able to do it with: https://devcenter.heroku.com/articles/github-integration#automatic-deploys

Mostly I think it's helpful for the audit log in heroku, or if we can customize the hip chat message it can link to the commit hash too,

**Comment by aaaschmitt** [comment]
Oh yeah we can just do this. 
1.) We have heroku  deploy from github instead of travis deploying to heroku
2.) but heroku waits for travis to pass before deploying
3.) that should give the web hook in hipchat the right username

**Comment by cycomachead** [comment]
Yeah, and at that time maybe we can move the build message to the dev integrations room?

Oooh we can add travis status as a notification too.

**Comment by aaaschmitt** [comment]
I actually enabled the automatic deploy from heroku and removed the deploy from travis but it didn't seem to do anything. Do you think you could take a look at this? @cycomachead

**Comment by aaaschmitt** [comment]
I'm worried it might be because I'm not an owner of cs10 but idk

**Comment by cycomachead** [comment]
Sure. Will do in a few hours. I can also make you an owner too.

**Comment by cycomachead** [comment]
Fixed! There was a Github app permissions level. I had to go into settings and specifically grant the heroku app access to CS10.
