### ISSUE TITLE
Fix travis badge link

### ISSUE THREAD

**Issue by cycomachead** [cs10/Alonzo#98]

**Comment by aaaschmitt** [comment]
What is wrong......

**Comment by cycomachead** [comment]
It doesn't link to travis....?

**Comment by aaaschmitt** [comment]
oh shit wtf....haha

**Comment by aaaschmitt** [comment]
oh didn't realize that......

**Comment by aaaschmitt** [comment]
I can take care of it. When you make issues like this though maybe say something helpful like that cuz unless I click the link I don't know what you're talking about.

**Comment by cycomachead** [comment]
Well I was going to get to it, but usually it's cuz Im in the middle of something...

**Comment by aaaschmitt** [comment]
lol it's not fixed. It's just a link now. Make it an img tag

**Comment by aaaschmitt** [comment]
nvm now it's good

**Comment by cycomachead** [comment]
Lol yeah... I reversed the text and image link...
