### ISSUE TITLE
Clear unused brain data before the semester

### ISSUE THREAD

**Issue by aaaschmitt** [cs10/Alonzo#99]

**Comment by cycomachead** [comment]
We should add a command like "RESET" and  then make it confirm the reset

**Comment by aaaschmitt** [comment]
yeah that would be pretty cool. Could probably do it with a simple boolean. The problem is that there are some keys that are no longer being used that I want to clear out.

**Comment by cycomachead** [comment]
We might try this: http://redisdesktop.com

**Comment by aaaschmitt** [comment]
done with this.
